# -*- coding: utf-8 -*-
"""food_coded_cleaned

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qL1UEQoh__tOBfdmFUrZ-8LOBzm1eb4e
"""

import pandas as pd

# Load the dataset
file_path = "food_coded.csv"  # Ensure the file is in the same directory or provide the full path
data = pd.read_csv(file_path)

# Step 1: Inspect the dataset
print("First 5 rows of the dataset:")
print(data.head())
print("\nDataset Information:")
print(data.info())
print("\nSummary Statistics:")
print(data.describe())

# Step 2: Check for missing values
missing_values = data.isnull().sum()
print("\nMissing values in each column:")
print(missing_values)

# Step 4: Remove duplicates
data = data.drop_duplicates()


# Step 5: Ensure data consistency (e.g., standardize text format)
# Convert all text columns to lowercase for consistency
for col in data.select_dtypes(include=['object']):
    data[col] = data[col].str.lower()


# Step 6: Verify cleaning
print("\nDataset Information after cleaning:")
print(data.info())

# Step 7: Save the cleaned dataset
cleaned_file_path = "food_coded_cleaned.csv"
data.to_csv(cleaned_file_path, index=False)
print(f"\nCleaned dataset saved to {cleaned_file_path}.")